version: "3.8"

services:
  countrycounter:
    image: ghcr.io/korjavin/countrycounter:2d7c833b42d006dda9db86bf9e2ca80009e80577
    container_name: countrycounter
    volumes:
      - cc-data:/app/backend
    networks:
      - ${NETWORK_NAME:-vaultwarden_default}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.countrycounter.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.countrycounter.entrypoints=websecure"
      - "traefik.http.routers.countrycounter.tls.certresolver=myresolver"
      - "io.containers.autoupdate=image"
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - DB_PATH=/app/backend/data.db

networks:
  vaultwarden_default:
    external: true

volumes:
  cc-data: