package main

// CountryBorders maps each country to its neighboring countries
// Names match exactly with countries.geo.json
var CountryBorders = map[string][]string{
	"Afghanistan":                       {"Iran", "Pakistan", "Turkmenistan", "Uzbekistan", "Tajikistan", "China"},
	"Albania":                           {"Greece", "North Macedonia", "Kosovo", "Montenegro"},
	"Algeria":                           {"Morocco", "Tunisia", "Libya", "Niger", "Mali", "Mauritania", "Western Sahara"},
	"Angola":                            {"Namibia", "Zambia", "Congo, Democratic Republic of the", "Congo, Republic of the"},
	"Argentina":                         {"Chile", "Bolivia", "Paraguay", "Brazil", "Uruguay"},
	"Armenia":                           {"Turkey", "Georgia", "Azerbaijan", "Iran"},
	"Australia":                         {},
	"Austria":                           {"Germany", "Czechia", "Slovakia", "Hungary", "Slovenia", "Italy", "Switzerland"},
	"Azerbaijan":                        {"Russia", "Georgia", "Armenia", "Iran", "Turkey"},
	"Bahamas":                           {},
	"Bangladesh":                        {"India", "Myanmar"},
	"Belarus":                           {"Latvia", "Lithuania", "Poland", "Ukraine", "Russia"},
	"Belgium":                           {"France", "Luxembourg", "Germany", "Netherlands"},
	"Belize":                            {"Mexico", "Guatemala"},
	"Benin":                             {"Togo", "Burkina Faso", "Niger", "Nigeria"},
	"Bhutan":                            {"China", "India"},
	"Bolivia":                           {"Peru", "Brazil", "Paraguay", "Argentina", "Chile"},
	"Bosnia and Herzegovina":            {"Croatia", "Serbia", "Montenegro"},
	"Botswana":                          {"Namibia", "Zambia", "Zimbabwe", "South Africa"},
	"Brazil":                            {"French Guiana", "Suriname", "Guyana", "Venezuela", "Colombia", "Peru", "Bolivia", "Paraguay", "Argentina", "Uruguay"},
	"Brunei":                            {"Malaysia"},
	"Bulgaria":                          {"Romania", "Serbia", "North Macedonia", "Greece", "Turkey"},
	"Burkina Faso":                      {"Mali", "Niger", "Benin", "Togo", "Ghana", "Cote d'Ivoire"},
	"Burundi":                           {"Rwanda", "Tanzania", "Congo, Democratic Republic of the"},
	"Cambodia":                          {"Thailand", "Laos", "Vietnam"},
	"Cameroon":                          {"Nigeria", "Chad", "Central African Republic", "Congo, Republic of the", "Gabon", "Equatorial Guinea"},
	"Canada":                            {"United States of America"},
	"Central African Republic":          {"Chad", "Sudan", "South Sudan", "Congo, Democratic Republic of the", "Congo, Republic of the", "Cameroon"},
	"Chad":                              {"Libya", "Sudan", "Central African Republic", "Cameroon", "Nigeria", "Niger"},
	"Chile":                             {"Peru", "Bolivia", "Argentina"},
	"China":                             {"North Korea", "Russia", "Mongolia", "Kazakhstan", "Kyrgyzstan", "Tajikistan", "Afghanistan", "Pakistan", "India", "Nepal", "Bhutan", "Myanmar", "Laos", "Vietnam"},
	"Colombia":                          {"Panama", "Venezuela", "Brazil", "Peru", "Ecuador"},
	"Congo, Democratic Republic of the": {"Congo, Republic of the", "Central African Republic", "South Sudan", "Uganda", "Rwanda", "Burundi", "Tanzania", "Zambia", "Angola"},
	"Congo, Republic of the":            {"Gabon", "Cameroon", "Central African Republic", "Congo, Democratic Republic of the", "Angola"},
	"Costa Rica":                        {"Nicaragua", "Panama"},
	"Cote d'Ivoire":                     {"Liberia", "Guinea", "Mali", "Burkina Faso", "Ghana"},
	"Croatia":                           {"Slovenia", "Hungary", "Serbia", "Bosnia and Herzegovina", "Montenegro"},
	"Cuba":                              {},
	"Cyprus":                            {},
	"Czechia":                           {"Germany", "Poland", "Slovakia", "Austria"},
	"Denmark":                           {"Germany"},
	"Djibouti":                          {"Eritrea", "Ethiopia", "Somalia"},
	"Dominican Republic":                {"Haiti"},
	"Ecuador":                           {"Colombia", "Peru"},
	"Egypt":                             {"Libya", "Sudan", "Israel"},
	"El Salvador":                       {"Guatemala", "Honduras"},
	"Equatorial Guinea":                 {"Cameroon", "Gabon"},
	"Eritrea":                           {"Sudan", "Ethiopia", "Djibouti"},
	"Estonia":                           {"Russia", "Latvia"},
	"Eswatini":                          {"Mozambique", "South Africa"},
	"Ethiopia":                          {"Eritrea", "Djibouti", "Somalia", "Kenya", "South Sudan", "Sudan"},
	"Fiji":                              {},
	"Finland":                           {"Norway", "Sweden", "Russia"},
	"France":                            {"Belgium", "Luxembourg", "Germany", "Switzerland", "Italy", "Spain"},
	"Gabon":                             {"Equatorial Guinea", "Cameroon", "Congo, Republic of the"},
	"Gambia":                            {"Senegal"},
	"Georgia":                           {"Russia", "Azerbaijan", "Armenia", "Turkey"},
	"Germany":                           {"Denmark", "Poland", "Czechia", "Austria", "Switzerland", "France", "Luxembourg", "Belgium", "Netherlands"},
	"Ghana":                             {"Cote d'Ivoire", "Burkina Faso", "Togo"},
	"Greece":                            {"Albania", "North Macedonia", "Bulgaria", "Turkey"},
	"Guatemala":                         {"Mexico", "Belize", "Honduras", "El Salvador"},
	"Guinea":                            {"Guinea-Bissau", "Senegal", "Mali", "Cote d'Ivoire", "Liberia", "Sierra Leone"},
	"Guinea-Bissau":                     {"Senegal", "Guinea"},
	"Guyana":                            {"Venezuela", "Brazil", "Suriname"},
	"Haiti":                             {"Dominican Republic"},
	"Honduras":                          {"Guatemala", "El Salvador", "Nicaragua"},
	"Hungary":                           {"Slovakia", "Ukraine", "Romania", "Serbia", "Croatia", "Slovenia", "Austria"},
	"Iceland":                           {},
	"India":                             {"Pakistan", "China", "Nepal", "Bhutan", "Bangladesh", "Myanmar"},
	"Indonesia":                         {"Papua New Guinea", "Timor-Leste", "Malaysia"},
	"Iran":                              {"Turkey", "Iraq", "Kuwait", "Saudi Arabia", "United Arab Emirates", "Oman", "Afghanistan", "Pakistan", "Turkmenistan", "Azerbaijan", "Armenia"},
	"Iraq":                              {"Turkey", "Iran", "Kuwait", "Saudi Arabia", "Jordan", "Syria"},
	"Ireland":                           {"United Kingdom"},
	"Israel":                            {"Lebanon", "Syria", "Jordan", "Egypt"},
	"Italy":                             {"France", "Switzerland", "Austria", "Slovenia"},
	"Jamaica":                           {},
	"Japan":                             {},
	"Jordan":                            {"Syria", "Iraq", "Saudi Arabia", "Israel"},
	"Kazakhstan":                        {"Russia", "China", "Kyrgyzstan", "Uzbekistan", "Turkmenistan"},
	"Kenya":                             {"Somalia", "Ethiopia", "South Sudan", "Uganda", "Tanzania"},
	"Kosovo":                            {"Serbia", "North Macedonia", "Albania", "Montenegro"},
	"Kuwait":                            {"Iraq", "Saudi Arabia"},
	"Kyrgyzstan":                        {"Kazakhstan", "China", "Tajikistan", "Uzbekistan"},
	"Laos":                              {"China", "Myanmar", "Thailand", "Cambodia", "Vietnam"},
	"Latvia":                            {"Estonia", "Russia", "Belarus", "Lithuania"},
	"Lebanon":                           {"Syria", "Israel"},
	"Lesotho":                           {"South Africa"},
	"Liberia":                           {"Sierra Leone", "Guinea", "Cote d'Ivoire"},
	"Libya":                             {"Tunisia", "Algeria", "Niger", "Chad", "Sudan", "Egypt"},
	"Lithuania":                         {"Latvia", "Belarus", "Poland", "Russia"},
	"Luxembourg":                        {"Belgium", "Germany", "France"},
	"Madagascar":                        {},
	"Malawi":                            {"Tanzania", "Mozambique", "Zambia"},
	"Malaysia":                          {"Thailand", "Indonesia", "Brunei"},
	"Mali":                              {"Senegal", "Mauritania", "Algeria", "Niger", "Burkina Faso", "Cote d'Ivoire", "Guinea"},
	"Malta":                             {},
	"Mauritania":                        {"Western Sahara", "Algeria", "Mali", "Senegal"},
	"Mexico":                            {"United States of America", "Guatemala", "Belize"},
	"Moldova":                           {"Romania", "Ukraine"},
	"Mongolia":                          {"Russia", "China"},
	"Montenegro":                        {"Croatia", "Bosnia and Herzegovina", "Serbia", "Kosovo", "Albania"},
	"Morocco":                           {"Spain", "Algeria", "Western Sahara"},
	"Mozambique":                        {"Tanzania", "Malawi", "Zambia", "Zimbabwe", "South Africa", "Eswatini"},
	"Myanmar":                           {"Bangladesh", "India", "China", "Laos", "Thailand"},
	"Namibia":                           {"Angola", "Zambia", "Botswana", "South Africa"},
	"Nepal":                             {"China", "India"},
	"Netherlands":                       {"Germany", "Belgium"},
	"New Zealand":                       {},
	"Nicaragua":                         {"Honduras", "Costa Rica"},
	"Niger":                             {"Libya", "Chad", "Nigeria", "Benin", "Burkina Faso", "Mali", "Algeria"},
	"Nigeria":                           {"Benin", "Niger", "Chad", "Cameroon"},
	"North Korea":                       {"China", "Russia", "South Korea"},
	"North Macedonia":                   {"Kosovo", "Serbia", "Bulgaria", "Greece", "Albania"},
	"Norway":                            {"Finland", "Sweden", "Russia"},
	"Oman":                              {"United Arab Emirates", "Saudi Arabia", "Yemen"},
	"Pakistan":                          {"Iran", "Afghanistan", "China", "India"},
	"Panama":                            {"Costa Rica", "Colombia"},
	"Papua New Guinea":                  {"Indonesia"},
	"Paraguay":                          {"Argentina", "Bolivia", "Brazil"},
	"Peru":                              {"Ecuador", "Colombia", "Brazil", "Bolivia", "Chile"},
	"Philippines":                       {},
	"Poland":                            {"Germany", "Czechia", "Slovakia", "Ukraine", "Belarus", "Lithuania", "Russia"},
	"Portugal":                          {"Spain"},
	"Qatar":                             {"Saudi Arabia"},
	"Romania":                           {"Ukraine", "Moldova", "Hungary", "Serbia", "Bulgaria"},
	"Russia":                            {"Norway", "Finland", "Estonia", "Latvia", "Lithuania", "Poland", "Belarus", "Ukraine", "Georgia", "Azerbaijan", "Kazakhstan", "China", "Mongolia", "North Korea"},
	"Rwanda":                            {"Uganda", "Tanzania", "Burundi", "Congo, Democratic Republic of the"},
	"Saudi Arabia":                      {"Jordan", "Iraq", "Kuwait", "Qatar", "United Arab Emirates", "Oman", "Yemen"},
	"Senegal":                           {"Mauritania", "Mali", "Guinea", "Guinea-Bissau", "Gambia"},
	"Serbia":                            {"Hungary", "Romania", "Bulgaria", "North Macedonia", "Kosovo", "Montenegro", "Bosnia and Herzegovina", "Croatia"},
	"Sierra Leone":                      {"Guinea", "Liberia"},
	"Slovakia":                          {"Poland", "Czechia", "Austria", "Hungary", "Ukraine"},
	"Slovenia":                          {"Austria", "Italy", "Hungary", "Croatia"},
	"Solomon Islands":                   {},
	"Somalia":                           {"Djibouti", "Ethiopia", "Kenya"},
	"South Africa":                      {"Namibia", "Botswana", "Zimbabwe", "Mozambique", "Eswatini", "Lesotho"},
	"South Korea":                       {"North Korea"},
	"South Sudan":                       {"Sudan", "Ethiopia", "Kenya", "Uganda", "Congo, Democratic Republic of the", "Central African Republic"},
	"Spain":                             {"Portugal", "France", "Morocco"},
	"Sri Lanka":                         {},
	"Sudan":                             {"Egypt", "Libya", "Chad", "Central African Republic", "South Sudan", "Ethiopia", "Eritrea"},
	"Suriname":                          {"Guyana", "Brazil", "French Guiana"},
	"Sweden":                            {"Norway", "Finland"},
	"Switzerland":                       {"France", "Germany", "Austria", "Italy"},
	"Syria":                             {"Turkey", "Iraq", "Jordan", "Israel", "Lebanon"},
	"Taiwan":                            {},
	"Tajikistan":                        {"Afghanistan", "China", "Kyrgyzstan", "Uzbekistan"},
	"Tanzania":                          {"Kenya", "Uganda", "Rwanda", "Burundi", "Congo, Democratic Republic of the", "Zambia", "Malawi", "Mozambique"},
	"Thailand":                          {"Myanmar", "Laos", "Cambodia", "Malaysia"},
	"Timor-Leste":                       {"Indonesia"},
	"Togo":                              {"Ghana", "Burkina Faso", "Benin"},
	"Trinidad and Tobago":               {},
	"Tunisia":                           {"Algeria", "Libya"},
	"Turkey":                            {"Greece", "Bulgaria", "Georgia", "Armenia", "Azerbaijan", "Iran", "Iraq", "Syria"},
	"Turkmenistan":                      {"Kazakhstan", "Uzbekistan", "Afghanistan", "Iran"},
	"Uganda":                            {"South Sudan", "Kenya", "Tanzania", "Rwanda", "Congo, Democratic Republic of the"},
	"Ukraine":                           {"Poland", "Slovakia", "Hungary", "Romania", "Moldova", "Russia", "Belarus"},
	"United Arab Emirates":              {"Saudi Arabia", "Oman"},
	"United Kingdom":                    {"Ireland"},
	"United States of America":          {"Canada", "Mexico"},
	"Uruguay":                           {"Brazil", "Argentina"},
	"Uzbekistan":                        {"Kazakhstan", "Tajikistan", "Kyrgyzstan", "Afghanistan", "Turkmenistan"},
	"Vanuatu":                           {},
	"Venezuela":                         {"Colombia", "Brazil", "Guyana"},
	"Vietnam":                           {"China", "Laos", "Cambodia"},
	"Western Sahara":                    {"Morocco", "Algeria", "Mauritania"},
	"Yemen":                             {"Saudi Arabia", "Oman"},
	"Zambia":                            {"Congo, Democratic Republic of the", "Tanzania", "Malawi", "Mozambique", "Zimbabwe", "Botswana", "Namibia", "Angola"},
	"Zimbabwe":                          {"Zambia", "Mozambique", "South Africa", "Botswana"},
}

// CountryAreas maps each country to its area in square kilometers (approximate)
// Names match exactly with countries.geo.json
var CountryAreas = map[string]float64{
	"Russia":                            17098242,
	"Canada":                            9984670,
	"United States of America":          9833517,
	"China":                             9596961,
	"Brazil":                            8515767,
	"Australia":                         7692024,
	"India":                             3287263,
	"Argentina":                         2780400,
	"Kazakhstan":                        2724900,
	"Algeria":                           2381741,
	"Congo, Democratic Republic of the": 2344858,
	"Saudi Arabia":                      2149690,
	"Mexico":                            1964375,
	"Indonesia":                         1904569,
	"Libya":                             1759540,
	"Iran":                              1648195,
	"Mongolia":                          1564110,
	"Peru":                              1285216,
	"Chad":                              1284000,
	"Niger":                             1267000,
	"Angola":                            1246700,
	"Mali":                              1240192,
	"South Africa":                      1221037,
	"Colombia":                          1141748,
	"Ethiopia":                          1104300,
	"Bolivia":                           1098581,
	"Mauritania":                        1030700,
	"Egypt":                             1001450,
	"Tanzania":                          947303,
	"Nigeria":                           923768,
	"Venezuela":                         916445,
	"Pakistan":                          881912,
	"Namibia":                           825615,
	"Mozambique":                        801590,
	"Turkey":                            783562,
	"Chile":                             756102,
	"Zambia":                            752612,
	"Myanmar":                           676578,
	"Afghanistan":                       652864,
	"Somalia":                           637657,
	"Central African Republic":          622984,
	"South Sudan":                       619745,
	"Ukraine":                           603500,
	"Madagascar":                        587041,
	"Botswana":                          582000,
	"Kenya":                             580367,
	"France":                            551695,
	"Yemen":                             527968,
	"Thailand":                          513120,
	"Spain":                             505990,
	"Turkmenistan":                      488100,
	"Cameroon":                          475442,
	"Papua New Guinea":                  462840,
	"Sweden":                            450295,
	"Uzbekistan":                        447400,
	"Morocco":                           446550,
	"Iraq":                              438317,
	"Paraguay":                          406752,
	"Zimbabwe":                          390757,
	"Norway":                            385207,
	"Japan":                             377930,
	"Germany":                           357114,
	"Congo, Republic of the":            342000,
	"Finland":                           338424,
	"Vietnam":                           331212,
	"Malaysia":                          330803,
	"Cote d'Ivoire":                     322463,
	"Poland":                            312696,
	"Oman":                              309500,
	"Italy":                             301336,
	"Philippines":                       300000,
	"Ecuador":                           276841,
	"Burkina Faso":                      274222,
	"New Zealand":                       270467,
	"Gabon":                             267668,
	"Western Sahara":                    266000,
	"Guinea":                            245857,
	"United Kingdom":                    242495,
	"Uganda":                            241550,
	"Ghana":                             238533,
	"Romania":                           238391,
	"Laos":                              236800,
	"Guyana":                            214969,
	"Belarus":                           207600,
	"Kyrgyzstan":                        199951,
	"Senegal":                           196722,
	"Syria":                             185180,
	"Cambodia":                          181035,
	"Uruguay":                           176215,
	"Suriname":                          163820,
	"Tunisia":                           163610,
	"Bangladesh":                        147570,
	"Nepal":                             147516,
	"Tajikistan":                        143100,
	"Greece":                            131957,
	"Nicaragua":                         130373,
	"North Korea":                       120538,
	"Malawi":                            118484,
	"Eritrea":                           117600,
	"Benin":                             114763,
	"Honduras":                          112492,
	"Liberia":                           111369,
	"Bulgaria":                          110879,
	"Cuba":                              109884,
	"Guatemala":                         108889,
	"Iceland":                           103000,
	"South Korea":                       100210,
	"Hungary":                           93028,
	"Portugal":                          92090,
	"Jordan":                            89342,
	"Serbia":                            88361,
	"Azerbaijan":                        86600,
	"Austria":                           83871,
	"United Arab Emirates":              83600,
	"Czechia":                           78865,
	"Panama":                            75417,
	"Sierra Leone":                      71740,
	"Ireland":                           70273,
	"Georgia":                           69700,
	"Sri Lanka":                         65610,
	"Lithuania":                         65300,
	"Latvia":                            64559,
	"Togo":                              56785,
	"Croatia":                           56594,
	"Bosnia and Herzegovina":            51209,
	"Costa Rica":                        51100,
	"Slovakia":                          49037,
	"Dominican Republic":                48671,
	"Estonia":                           45227,
	"Denmark":                           42951,
	"Netherlands":                       41850,
	"Switzerland":                       41285,
	"Bhutan":                            38394,
	"Taiwan":                            36193,
	"Guinea-Bissau":                     36125,
	"Moldova":                           33846,
	"Belgium":                           30528,
	"Lesotho":                           30355,
	"Armenia":                           29743,
	"Solomon Islands":                   28896,
	"Albania":                           28748,
	"Equatorial Guinea":                 28051,
	"Burundi":                           27834,
	"Haiti":                             27750,
	"Rwanda":                            26338,
	"North Macedonia":                   25713,
	"Belize":                            22966,
	"Djibouti":                          23200,
	"El Salvador":                       21041,
	"Israel":                            20770,
	"Slovenia":                          20273,
	"Fiji":                              18272,
	"Kuwait":                            17818,
	"Eswatini":                          17364,
	"Timor-Leste":                       14919,
	"Bahamas":                           13943,
	"Montenegro":                        13812,
	"Vanuatu":                           12189,
	"Qatar":                             11586,
	"Gambia":                            11295,
	"Jamaica":                           10991,
	"Kosovo":                            10887,
	"Lebanon":                           10452,
	"Cyprus":                            9251,
	"Brunei":                            5765,
	"Trinidad and Tobago":               5130,
	"Malta":                             316,
}
